version: "3"
services:
  db:
    image: mariadb:10
    container_name: db
    tty: true
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    env_file: ./env
    networks:
      - node-app

  nginx:
    build:
      context: nginx
    container_name: nginx
    depends_on:
      - node
    restart: always
    ports:
      - "8080:80"
    networks:
      - node-app

  node:
    build:
      context: node
    container_name: node
    depends_on:
      - db
    ports:
      - "80"
    volumes:
      - $PWD/node/src:/app
      - node_modules:/app/node_modules
    entrypoint: "dockerize -wait tcp://db:3306 -timeout 60s nodemon server.js"
    env_file: ./env
    networks:
      - node-app

networks:
  node-app:
    driver: bridge

volumes: 
  node_modules:
